module.exports={
    PRODUCT_COLLECTION:'product',
    USER_COLLECTION:'user',
    BANNER_COLLECTION:'banner',
    VIDEO_COLLECTION:'video',
    CATEGORY_COLLECTION:'category',
    SLIDER_COLLECTION:'slider',
    BRAND_COLLECTION:'brand',
    PACKAGE_COLLECTION:'package',
}